-- Insertion order of leads (sheet order) so the sender can pick the next new lead with a query.
alter table public.leads add column seq bigint generated by default as identity;
-- Fast lookups for the every-minute sender and the reply checker.
create index leads_send_queue_idx on public.leads (account_id, status, next_at);
create index leads_pending_seq_idx on public.leads (account_id, seq) where status = 'pending';
create index leads_reply_check_idx on public.leads (account_id, last_checked_at) where thread_id is not null and replied_at is null;
create index events_sent_at_idx on public.events (at) where type = 'sent';
